yegor-sereda-dao3-hw
entertainment-veks/dao-3 pull request #1
Opened 2021-01-12 12:21 UTC by entertainment-veks

added Car, Driver and Manufacturer models
added ManufacturerDao + impl
added ManufacturerService + impl
added Injector
added controller (Application.java)

2021-01-12 13:25 UTC, Fedich09 requested changes

2021-01-12 13:25 UTC, Fedich09 commented on pom.xml
>  </project>
```suggestion
</project>

```
add empty line please

2021-01-12 13:25 UTC, Fedich09 commented on src/main/java/dao3/dao/impl/ManufacturerDaoImpl.java
> +            if (Storage.manufacturers.get(i).getId() == manufacturer.getId()) {
```suggestion
            if (Storage.manufacturers.get(i).getId() == manufacturer.getId()) {
```
you should compare objects with equals

2021-01-12 13:25 UTC, Fedich09 commented on src/main/java/dao3/dao/impl/ManufacturerDaoImpl.java
> +
```suggestion
        return Storage.manufacturers.remove(id);
```

2021-01-12 13:25 UTC, Fedich09 commented on src/main/java/dao3/model/Manufacturer.java
> +}
```suggestion
}
```
and you should add equals and hashCode methods

2021-01-12 13:39 UTC, Fedich09 approved these changes

2021-01-12 14:43 UTC, Sofasmile requested changes

2021-01-12 14:43 UTC, Sofasmile commented on pom.xml
> +            <groupId>junit</groupId>
do we need this dependency here?

2021-01-12 14:43 UTC, Sofasmile commented on src/main/java/dao3/dao/impl/ManufacturerDaoImpl.java
> +                .filter(m -> m.getId() == id)
what is the difference berween == and equals?

2021-01-12 14:43 UTC, Sofasmile commented on src/main/java/dao3/dao/impl/ManufacturerDaoImpl.java
> +            if (manufacturer.getId() == Storage.manufacturers.get(i).getId()) {
the same

2021-01-12 14:43 UTC, Sofasmile commented on src/main/java/dao3/dao/impl/ManufacturerDaoImpl.java
> +        return null;
return null is a bad practice, better throw exception

2021-01-12 14:43 UTC, Sofasmile commented on src/main/java/dao3/dao/impl/ManufacturerDaoImpl.java
> +        return Storage.manufacturers.removeIf(e -> e.getId() == id);
the same

2021-01-12 14:43 UTC, Sofasmile commented on src/main/java/dao3/db/Storage.java
> +    public static List<Car> cars = new ArrayList<>();
let's add final keyword to all lists

2021-01-12 14:43 UTC, Sofasmile commented on src/main/java/dao3/model/Car.java
> +    public Car(int id, String model, Manufacturer manufacturer, List<Driver> drivers) {
should we pass id through constructor? 
the same about drivers?
please, read checklist - https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/03_dao_service_checklist.html

2021-01-12 14:43 UTC, Sofasmile commented on src/main/java/dao3/model/Car.java
> +    private int id;
id should be Long and wrapper

2021-01-12 14:43 UTC, Sofasmile commented on src/main/java/dao3/model/Driver.java
> +    private long id;
and here

2021-01-12 14:43 UTC, Sofasmile commented on src/main/java/dao3/model/Driver.java
> +    public Driver(long id, String name, String licenceNumber) {
the same

2021-01-12 14:43 UTC, Sofasmile commented on src/main/java/dao3/model/Manufacturer.java
> +    private long id;
and here

2021-01-12 14:43 UTC, Sofasmile commented on src/main/java/dao3/service/impl/ManufactererServiceImpl.java
> +    ManufacturerDao manufacturerDao;
how about access modifier?

2021-01-12 14:43 UTC, Sofasmile commented on src/main/java/dao3/service/impl/ManufactererServiceImpl.java
> +        return manufacturerDao.get(id).orElse(null);
```suggestion
        return manufacturerDao.get(id).get();
```

2021-01-13 08:58 UTC, Sofasmile requested changes

2021-01-13 08:58 UTC, Sofasmile commented on src/main/java/dao3/dao/impl/ManufacturerDaoImpl.java
> +        throw new RuntimeException("Can't update, element doesn't exist");
```suggestion
        throw new RuntimeException("Can't update, element " + manufacturer + " doesn't exist");
```

2021-01-13 08:58 UTC, Sofasmile commented on src/main/java/dao3/model/Car.java
>          this.id = id;
```suggestion
    public Car(String model, Manufacturer manufacturer) {
```

2021-01-13 08:58 UTC, Sofasmile commented on src/main/java/dao3/model/Driver.java
> +        this.name = name;
```suggestion
    public Driver(String name, String licenceNumber) {
        this.name = name;
```

2021-01-13 11:23 UTC, Sofasmile approved these changes

2021-01-13 13:04 UTC, merged