Dao 9 new
entertainment-veks/dao-3 pull request #11
Opened 2021-01-26 12:40 UTC by entertainment-veks

2021-01-26 13:17 UTC, RomanDubovskyi requested changes
fix comments from the chat

2021-01-26 13:17 UTC, RomanDubovskyi commented on src/main/java/taxiservice/controller/driver/LoginDriverController.java
> +            HttpSession session = req.getSession();
```suggestion
        String password = req.getParameter("password");
        try {
            Driver input = authService.login(login, password);
            HttpSession session = req.getSession();
```

2021-01-26 13:28 UTC, RomanDubovskyi commented
fix comments that i left in channel jv_nov20

2021-01-26 14:29 UTC, RomanDubovskyi requested changes

2021-01-26 14:29 UTC, RomanDubovskyi commented on src/main/java/taxiservice/web/filter/AuthentificationFilter.java
> +        if (driverId == null || driverService.get(driverId) == null) {
can get() from driverService return null?

2021-01-26 14:29 UTC, RomanDubovskyi commented on src/main/java/taxiservice/web/filter/AuthentificationFilter.java
> +    private Set<String> links = new HashSet<>();
```suggestion
    private Set<String> allowedLinks = new HashSet<>();
```

2021-01-31 19:48 UTC, KseniiaMakarova approved these changes

2021-03-02 11:04 UTC, merged