yegor-sereda-dao5-hw
entertainment-veks/dao-3 pull request #3
Opened 2021-01-15 15:18 UTC by entertainment-veks

2021-01-15 17:23 UTC, NikolayFatkullin requested changes

2021-01-15 17:23 UTC, NikolayFatkullin commented on src/main/java/dao3/dao/GenericDao.java
> +    boolean delete(I i);
bad names of variables

2021-01-15 17:23 UTC, NikolayFatkullin commented on src/main/java/dao3/dao/jdbc/ManufacturerDaoJDBCImpl.java
> +            PreparedStatement stmt = connection
bad name of variable
```suggestion
            PreparedStatement statement = connection
```

2021-01-15 17:23 UTC, NikolayFatkullin commented on src/main/java/dao3/dao/jdbc/ManufacturerDaoJDBCImpl.java
> +            ResultSet rs = stmt.getGeneratedKeys();
same

2021-01-15 17:23 UTC, NikolayFatkullin commented on src/main/java/dao3/dao/jdbc/ManufacturerDaoJDBCImpl.java
> +            PreparedStatement stmt = connection
add PreparedStatement to try with resources and then, you don't need to close them, they will close automatically

2021-01-15 17:23 UTC, NikolayFatkullin commented on src/main/java/dao3/dao/jdbc/ManufacturerDaoJDBCImpl.java
> +                + " WHERE manufacturer_id = ?";
Checklist: Let’s use TRUE/FALSE instead of 1/0 with the deleted column in the SQL queries.

2021-01-15 17:23 UTC, NikolayFatkullin commented on src/main/java/dao3/dao/jdbc/ManufacturerDaoJDBCImpl.java
> +                        rs.getObject("manufacturer_country", String.class)));
Create a method that will create the Manufacturer object

2021-01-15 17:43 UTC, NikolayFatkullin requested changes

2021-01-15 17:43 UTC, NikolayFatkullin commented on src/main/java/dao3/dao/jdbc/ManufacturerDaoJDBCImpl.java
> +    }
```suggestion
    private Manufacturer newManufacturer(ResultSet resultSet) {
        //todo;
    }
```

2021-01-15 18:09 UTC, boroda4436 requested changes

2021-01-15 18:09 UTC, boroda4436 commented on src/main/java/dao3/dao/jdbc/DriverDaoJDBCImpl.java
> +public class DriverDaoJDBCImpl implements DriverDao {
remove this class from the current PR

2021-01-15 18:09 UTC, boroda4436 commented on src/main/java/dao3/dao/jdbc/ManufacturerDaoJDBCImpl.java
> +import java.sql.*;
?

2021-01-15 18:09 UTC, boroda4436 commented on src/main/java/dao3/db/Database.java
> +package dao3.db;
`dao3` is not a good package name. Let's name for example `taxiservice`

2021-01-15 18:09 UTC, boroda4436 commented on src/main/java/dao3/db/Database.java
> +public class Database {
this class is redundant

2021-01-15 18:09 UTC, boroda4436 commented on src/main/java/dao3/util/ConnectionUtil.java
> +        String url = "jdbc:mysql://localhost:3306/dao3?serverTimezone=UTC";
As well as package name `dao3` is not a good name. Consider renaming DB.

2021-01-15 18:09 UTC, boroda4436 commented on src/main/resources/init_db.sql
> +`manufacturer_name` VARCHAR(255) NOT NULL,
```suggestion
`name` VARCHAR(255) NOT NULL,
```

2021-01-15 18:09 UTC, boroda4436 commented on src/main/resources/init_db.sql
> +`manufacturer_country` VARCHAR(255) NOT NULL,
```suggestion
`country` VARCHAR(255) NOT NULL,
```
You already know this is manufacturer

2021-01-15 19:30 UTC, boroda4436 requested changes

2021-01-15 19:30 UTC, boroda4436 commented on src/main/java/taxiservice/Application.java
> +        long manufacturer1id = manufacturer1.getId();
```suggestion
        long toyotaManufacturerId = toyotaManufacturer.getId();
```

2021-01-15 19:30 UTC, boroda4436 commented on src/main/java/taxiservice/Application.java
> +        Manufacturer manufacturer1 = new Manufacturer("Toyota", "Japan");
```suggestion
        Manufacturer toyotaManufacturer = new Manufacturer("Toyota", "Japan");
```
Let's use meaningful names

2021-01-15 19:30 UTC, boroda4436 commented on src/main/java/taxiservice/Application.java
> +        Manufacturer manufacturer3 = new Manufacturer("Mazda", "Japan");
```suggestion
        Manufacturer mazdaManufacturer = new Manufacturer("Mazda", "Japan");
```

2021-01-15 19:30 UTC, boroda4436 commented on src/main/java/taxiservice/Application.java
> +        Manufacturer manufacturer2 = new Manufacturer("Nissan", "Japan");
the same

2021-01-15 19:30 UTC, boroda4436 commented on src/main/java/taxiservice/dao/jdbc/ManufacturerDaoJdbcImpl.java
> +                + "country = ? "
```suggestion
                + " country = ? "
```

2021-01-15 19:30 UTC, boroda4436 commented on src/main/java/taxiservice/dao/jdbc/ManufacturerDaoJdbcImpl.java
> +            return new Manufacturer(resultSet.getObject("name", String.class),
What about `id`?

2021-01-17 08:59 UTC, boroda4436 approved these changes

2021-01-19 14:44 UTC, merged