dao-6
entertainment-veks/dao-3 pull request #4
Opened 2021-01-19 15:08 UTC by entertainment-veks

2021-01-19 15:57 UTC, Fedich09 requested changes

2021-01-19 15:57 UTC, Fedich09 commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +    public static final String CARS_DRIVERS_TAB_NAME = "cars_drivers";
```suggestion
    public static final String CARS_DRIVERS_TAB_NAME = "cars_drivers";
```
I not sure, but I think this is bad practice

2021-01-19 15:57 UTC, Fedich09 commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +        query = "INSERT INTO " + CARS_DRIVERS_TAB_NAME + " (car_id, diver_id) VALUES (?, ?)";
better do this in separate method, and create new connection this is bad practice, you can use same connection and use separate method in end of try block, in this way you use just one connection

2021-01-19 15:57 UTC, Fedich09 commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +            result.setDrivers(getDrivers(result.getId()));
you can put this if/else block in try/catch and use the same connection in  method getDrivers()
```suggestion
            result.setDrivers(getDrivers(result.getId()));
```

2021-01-19 15:57 UTC, Fedich09 commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +                car.setDrivers(getDrivers(car.getId()));
same here
```suggestion
                car.setDrivers(getDrivers(car.getId()));
```

2021-01-19 15:57 UTC, Fedich09 commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +        query = "DELETE FROM " + CARS_DRIVERS_TAB_NAME
create separate method for delete and use same connection, create just new PreparedStatement 
```suggestion
        query = "DELETE FROM " + CARS_DRIVERS_TAB_NAME
```

2021-01-19 15:57 UTC, Fedich09 commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +        query = "INSERT INTO " + CARS_DRIVERS_TAB_NAME
```suggestion
        query = "INSERT INTO " + CARS_DRIVERS_TAB_NAME
```
create separate method for insert

2021-01-19 15:57 UTC, Fedich09 commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +                car.setDrivers(getDrivers(car.getId()));
```suggestion
                car.setDrivers(getDrivers(car.getId()));
```
put this method inside try/catch and use one connection please

2021-01-19 17:16 UTC, dmytro-hryhoruk requested changes

2021-01-19 17:16 UTC, dmytro-hryhoruk commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +    public static final String CARS_DRIVERS_TAB_NAME = "cars_drivers";
agree,  let's write query as it is.

2021-01-19 17:16 UTC, dmytro-hryhoruk commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +        query = "INSERT INTO " + CARS_DRIVERS_TAB_NAME + " (car_id, diver_id) VALUES (?, ?)";
also agree, let's fix this

2021-01-19 17:16 UTC, dmytro-hryhoruk commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +            result.setDrivers(getDrivers(result.getId()));
also agree)

2021-01-19 17:16 UTC, dmytro-hryhoruk commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +        }
let's catch these exceptions on upper lever(the places where you are calling this method)

2021-01-19 17:16 UTC, dmytro-hryhoruk commented on src/main/java/taxiservice/dao/jdbc/DriverDaoJdbcImpl.java
> +        Driver result = new Driver(null, null);
let's create and return Driver inside try catch

2021-01-19 17:16 UTC, dmytro-hryhoruk commented on src/main/java/taxiservice/dao/jdbc/DriverDaoJdbcImpl.java
> +                result.setLicenceNumber(resultSet.getObject("licence_number", String.class));
you can use newDriver() method here

2021-01-20 08:35 UTC, dmytro-hryhoruk approved these changes

2021-01-20 08:35 UTC, dmytro-hryhoruk commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +            }
you are using this logic in update method too. Let's move it to private method

2021-01-20 08:35 UTC, dmytro-hryhoruk commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +        List<Car> result = new ArrayList<>();
```suggestion
        List<Car> cars = new ArrayList<>();
```

2021-01-20 08:35 UTC, dmytro-hryhoruk commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +        }
?

2021-01-20 08:35 UTC, dmytro-hryhoruk commented on src/main/java/taxiservice/dao/jdbc/CarDaoJdbcImpl.java
> +        }
let's use one connection for update and delete operations(insert should be in the private method, but you can pass connection in this method too)

2021-01-20 10:32 UTC, merged